from enum import Enum
class ACTION(Enum):
    IGNORE = 0
    MOVE = 1
    COPY = 2


PING_CHAT_ID = 866684643604824115

EXCLUDE_CHAT_IDS = []


PING_MESSAGE_ACTION = ACTION.MOVE
PING_MESSAGE_WITH_TEXT_ACTION = ACTION.IGNORE

NEW_MESSAGE_PATTERN = '{message} from {author}'